# config.py
local_users = [
    {'candidate_id': 1, 'worksheet_name': 'test', 'include_easy_apply': 'yes'},
    # # {'candidate_id': 43, 'worksheet_name': 'Charlton Cunningham', 'include_easy_apply': 'no'},
    # # {'candidate_id': 47, 'worksheet_name': 'Jeffrey Anderson', 'include_easy_apply': 'no'},
    # {'candidate_id': 26, 'worksheet_name': 'Damon Gray', 'include_easy_apply': 'yes'},
    # # {'candidate_id': 29, 'worksheet_name': 'Jennifer Saylor', 'include_easy_apply': 'no'},
    # # {'candidate_id': 3, 'worksheet_name': 'Jeremy KloberSdanz', 'include_easy_apply': 'no'},
    # {'candidate_id': 18, 'worksheet_name': 'Derek Brown', 'include_easy_apply': 'no'},
    # {'candidate_id': 30, 'worksheet_name': 'Christopher Rouse', 'include_easy_apply': 'yes'},
    # # {'candidate_id': 4, 'worksheet_name': 'Doug Zeffer', 'include_easy_apply': 'no'},
    # {'candidate_id': 19, 'worksheet_name': 'Todd Barasch', 'include_easy_apply': 'no'},
    # # {'candidate_id': 5, 'worksheet_name': 'Chris Dugan', 'include_easy_apply': 'no'},
    # # {'candidate_id': 33, 'worksheet_name': 'Stephen Wells', 'include_easy_apply': 'no'},
    # {'candidate_id': 22, 'worksheet_name': 'Michael Tenney', 'include_easy_apply': 'no'},
    # {'candidate_id': 40, 'worksheet_name': 'Ryan Mattonen', 'include_easy_apply': 'yes'},
    # # {'candidate_id': 37, 'worksheet_name': 'Braedon Burgess', 'include_easy_apply': 'no'},
    # {'candidate_id': 32, 'worksheet_name': 'Kent Lyle', 'include_easy_apply': 'no'},
    # {'candidate_id': 14, 'worksheet_name': 'Jason Brady', 'include_easy_apply': 'no'},
    # {'candidate_id': 35, 'worksheet_name': 'Kimberly Skyes', 'include_easy_apply': 'yes'},
    # {'candidate_id': 20, 'worksheet_name': 'Patrick Bartleson', 'include_easy_apply': 'no'},
    # {'candidate_id': 38, 'worksheet_name': 'Ken Robertson', 'include_easy_apply': 'no'},
    # {'candidate_id': 24, 'worksheet_name': 'Joao Priori', 'include_easy_apply': 'no'},
    # # {'candidate_id': 17, 'worksheet_name': 'Tod Steward', 'include_easy_apply': 'no'},
    # {'candidate_id': 27, 'worksheet_name': 'Jerry Woodruff', 'include_easy_apply': 'no'},
    # {'candidate_id': 12, 'worksheet_name': 'Mollee Bekele', 'include_easy_apply': 'no'},
    # {'candidate_id': 36, 'worksheet_name': 'Robert Brightwell', 'include_easy_apply': 'no'},
    # # {'candidate_id': 46, 'worksheet_name': 'Angela Antoun Mafioli', 'include_easy_apply': 'no'},
    # {'candidate_id': 6, 'worksheet_name': 'Carla Taylor', 'include_easy_apply': 'no'},
    # {'candidate_id': 25, 'worksheet_name': 'Miles Nukwu', 'include_easy_apply': 'no'},
    # # Add more users as needed
]

# config.py
online_users = [
    # # # {'candidate_id': 7, 'worksheet_name': 'Steven Smith', 'include_easy_apply': 'no'},
    # {'candidate_id': 8, 'worksheet_name': 'Dennis Makowski', 'include_easy_apply': 'no'},
    # # # {'candidate_id': 9, 'worksheet_name': 'Paulo Jeronymo', 'include_easy_apply': 'no'},
    # # # {'candidate_id': 11, 'worksheet_name': 'Ricardo Bravo', 'include_easy_apply': 'no'},
    # # {'candidate_id': 15, 'worksheet_name': 'Jason Gwin', 'include_easy_apply': 'yes'},
    # # {'candidate_id': 16, 'worksheet_name': 'John Scarth', 'include_easy_apply': 'no'},
    # # {'candidate_id': 17, 'worksheet_name': 'Jason Bernstein', 'include_easy_apply': 'no'},
    # # {'candidate_id': 18, 'worksheet_name': 'Peter Breault', 'include_easy_apply': 'no'},
    # {'candidate_id': 21, 'worksheet_name': 'Gary Hartzell', 'include_easy_apply': 'no'},
]
